# Generated by Django 2.0.4 on 2018-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptodo', '0002_auto_20180423_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateField(),
        ),
    ]
