# Generated by Django 2.0.4 on 2018-04-25 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('title', models.CharField(max_length=3000)),
                ('status', models.CharField(choices=[('P', 'pending'), ('C', 'completed')], max_length=1)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uptodo.TodoTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
