# Generated by Django 2.0.4 on 2018-04-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uptodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uptodo.TodoTask'),
        ),
    ]
