# Generated by Django 2.0.4 on 2018-04-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptodo', '0003_auto_20180423_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
